services:
  app:
    build:
      context: ./spring-ecomerce
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy   # espera a que MySQL pase healthcheck
    environment:
      JDBC_URL: jdbc:mysql://db:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      JDBC_USERNAME: root
      JDBC_PASSWORD: cactus3746
    healthcheck:
      # da un poco más de tiempo para que levante Spring
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: cactus3746
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:
